name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: tests_and_lint
    # We test on `macos-latest` to accurately reflect
    # the core Wasm binary that we attach to the releases,
    # which is built on the latest macOS too.
    # This is also helpful for testing fuel
    # consumption in tests.
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasmtime-cli
        env:
          WASMTIME_VERSION: 8.0.0
        run: |
          wget -nv 'https://github.com/bytecodealliance/wasmtime/releases/download/v${{ env.WASMTIME_VERSION }}/wasmtime-v${{ env.WASMTIME_VERSION }}-x86_64-macos.tar.xz' -O /tmp/wasmtime.tar.xz
          mkdir /tmp/wasmtime
          tar xvf /tmp/wasmtime.tar.xz --strip-components=1 -C /tmp/wasmtime
          echo "/tmp/wasmtime" >> $GITHUB_PATH

      - name: Install cargo-wasi
        run: cargo install cargo-wasi

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Tests
        # Everything but WPT
        run: make test-quickjs-wasm-rs test-javy test-apis test-core test-cli

      - name: Check benchmarks
        run: make check-bench

      - name: Lint
        run: make fmt
